## Q2 - Feedforward Network (Forward Pass + RMSE + Gradients)


Define Functions and Given Parameters

In [1]:
import numpy as np

# Activation functions
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

# Given weights/biases and input
W1 = np.array([[0.1, 0.2],
               [-0.6, 0.3],
               [0.5, -0.4]])
b1 = np.array([[0.2],
               [-0.3],
               [0.3]])

W2 = np.array([[0.1],
               [-0.3],
               [0.4]])
b2 = -0.15

X = np.array([[1.2],
              [1.8]])
y_true = 0.7


Forward Pass + RMSE

In [2]:
# Forward pass
Z1 = W1 @ X + b1          # pre-activation of hidden layer
A1 = relu(Z1)             # activation of hidden layer (ReLU)

Z2 = (W2.T @ A1).item() + b2   # pre-activation of output (scalar)
y_hat = sigmoid(Z2)            # final output

# RMSE for a single sample: sqrt((y_hat - y)^2) = abs(y_hat - y)
rmse = np.sqrt((y_hat - y_true)**2)

print("Z1:\n", Z1)
print("A1:\n", A1)
print("Z2:", Z2)
print("y_hat:", y_hat)
print("RMSE:", rmse)


Z1:
 [[ 0.68]
 [-0.48]
 [ 0.18]]
A1:
 [[0.68]
 [0.  ]
 [0.18]]
Z2: -0.010000000000000037
y_hat: 0.49750002083312495
RMSE: 0.202499979166875


Gradients for Layer 2 (dL/dW2 and dL/db2)

In [3]:
# Error term
e = y_hat - y_true

# For single-sample RMSE: L = |e|
# dL/dy_hat = sign(e) (when e != 0)
dL_dyhat = 1.0 if e > 0 else (-1.0 if e < 0 else 0.0)

# y_hat = sigmoid(Z2) => dy_hat/dZ2 = y_hat*(1 - y_hat)
dyhat_dZ2 = y_hat * (1.0 - y_hat)

# Chain rule
dL_dZ2 = dL_dyhat * dyhat_dZ2

# Z2 = W2^T A1 + b2
dL_db2 = dL_dZ2
dL_dW2 = dL_dZ2 * A1   # same shape as W2

print("dL/db2:", dL_db2)
print("dL/dW2:\n", dL_dW2)


dL/db2: -0.2499937501041652
dL/dW2:
 [[-0.16999575]
 [-0.        ]
 [-0.04499888]]
